# =============================================================================
# EnvNet-v2 Model Hyperparameter Space
# =============================================================================
# Defines search space for EnvNet-v2 model constructor parameters.
# Preprocessing and augmentation parameters are handled automatically by model config.
# =============================================================================

model:
  # Dropout rate for regularization in classifier layers
  dropout:
    type: float
    low: 0.1
    high: 0.7
    log: false 
