# =============================================================================
# Loss Function Hyperparameter Space (Anti-Overfitting Focus)
# =============================================================================
# Defines search space for loss function parameters.
# Ranges optimized for overfitting prevention after observing extreme overfitting
# in EnvNet-v2 (0.92 val acc vs 0.43 test acc).
# =============================================================================

# Loss function hyperparameters
loss:
  # Label smoothing - INCREASED focus for regularization
  # Critical for preventing overconfident predictions and overfitting
  label_smoothing:
    type: float
    low: 0.05      # Higher minimum to ensure some smoothing (was 0.0)
    high: 0.4      # Higher maximum for stronger regularization (was 0.3)
    log: false 