# Hyperparameter space for loss function parameters
# This file defines the search space for loss-related hyperparameters

# Loss function hyperparameters
loss:
  # Label smoothing for cross-entropy loss
  label_smoothing:
    type: float
    low: 0.0
    high: 0.3
    log: false 