# Hyperparameter space for training parameters
# This file defines the search space for training-related hyperparameters

# Optimizer hyperparameters
optimizer:
  # Learning rate with log scale
  lr:
    type: float
    low: 1e-4
    high: 1e-2
    log: true
  
  # Weight decay for regularization
  weight_decay:
    type: float
    low: 1e-6
    high: 1e-2
    log: true

# Scheduler hyperparameters
scheduler:
  # T_max for CosineAnnealingLR (will be set to max_epochs)
  # This is more of a derived parameter, but can be tuned
  T_max:
    type: int
    low: 50
    high: 200
    log: false

# Training configuration
trainer:
  # Maximum number of epochs
  max_epochs:
    type: int
    low: 50
    high: 200
    log: false

# Batch size (categorical for common powers of 2)
batch_size:
  type: categorical
  choices: [16, 32, 64, 128]

# Data augmentation (if supported by dataset)
dataset:
  augment:
    type: categorical
    # choices: [true, false] 
    choices: [false] 