# =============================================================================
# Training Hyperparameter Space
# =============================================================================
# Defines search space for training-related hyperparameters.
# Model-specific preprocessing parameters are handled automatically by model configs.
# =============================================================================

# Optimizer hyperparameters
optimizer:
  # Learning rate with log scale
  lr:
    type: float
    low: 1e-4
    high: 1e-2
    log: true
  
  # Weight decay for regularization
  weight_decay:
    type: float
    low: 1e-6
    high: 1e-2
    log: true

# Scheduler hyperparameters
scheduler:
  # T_max for CosineAnnealingLR (will be set to max_epochs)
  T_max:
    type: int
    low: 50
    high: 200
    log: false

# Training configuration
trainer:
  # Maximum number of epochs
  max_epochs:
    type: int
    low: 50
    high: 200
    log: false

# Batch size (categorical for common powers of 2)
batch_size:
  type: categorical
  choices: [16, 32, 64, 128]

# Dataset-level augmentation (model-specific defaults handled automatically)
dataset:
  # Mixup alpha parameter (used when enable_mixup=true, model-specific defaults applied)
  mixup_alpha:
    type: float
    low: 0.1
    high: 2.0
    log: false
  
  # Override model-specific augmentation defaults (optional)
  enable_bc_mixing:
    type: categorical
    choices: [true, false]
  
  enable_mixup:
    type: categorical
    choices: [true, false] 