# =============================================================================
# AST Model Hyperparameter Space
# =============================================================================
# Defines search space for AST model constructor parameters.
# Preprocessing and augmentation parameters are handled automatically by model config.
# =============================================================================

model:
  # Patch size for transformer patches (affects model capacity and resolution)
  # NOTE: Must be 16 to match pretrained ViT models (all have patch16 in name)
  patch_size:
    type: categorical
    choices: [16]
  
  # Patch stride for patch extraction (affects overlap and computational cost)
  # NOTE: Must be <= patch_size (16) and >= overlap
  patch_stride:
    type: categorical
    choices: [8, 10, 12, 14, 16]
  
  # Overlap between patches (affects information sharing)
  # NOTE: Must be < patch_size (16) and <= patch_stride
  overlap:
    type: categorical
    choices: [4, 6, 8]
  
  # Pretrained Vision Transformer model (different capacities)
  pretrained_model:
    type: categorical
    choices: [
      "deit_tiny_patch16_224",
      "deit_small_patch16_224", 
      "deit_base_patch16_224",
      "deit_base_patch16_384"
    ]
  dataset_overrides:
    augment:
      time_mask:
        type: int
        low: 0
        high: 300
        log: false
      freq_mask:
        type: int
        low: 0
        high: 80
        log: false
    preprocessing_config:
      n_mels:
        type: int
        low: 64
        high: 256
        log: false
      normalize:
        type: categorical
        choices: [true, false]
      target_mean:
        type: float
        low: -1.0
        high: 1.0
        log: false
      target_std:
        type: float
        low: 0.1
        high: 1.0
        log: false
