# =============================================================================
# EnvNet-v2 Model Hyperparameter Space (Anti-Overfitting Focus)
# =============================================================================
# Defines search space for EnvNet-v2 model constructor parameters.
# Ranges optimized for overfitting prevention after observing extreme overfitting
# (0.92 val acc vs 0.43 test acc). Focus on high dropout rates.
# =============================================================================

model:
  # Dropout rate - SIGNIFICANTLY INCREASED for overfitting prevention
  dropout:
    type: float
    low: 0.6       # Much higher minimum (was 0.1)
    high: 0.9      # Higher maximum (was 0.7)
    log: false

  # Dataset overrides for EnvNet-v2 augmentation - ENABLE for regularization
  dataset_overrides:
    preprocessing_config:
      # Window length variation for data diversity
      window_length:
        type: float
        low: 5.0     # Fixed at 5.0 seconds to match EnvNet-v2 input size
        high: 5.0    # Fixed at 5.0 seconds to match EnvNet-v2 input size
        log: false
      
      # Padding ratio for random cropping variation
      padding_ratio:
        type: float
        low: 0.5     # Fixed at 0.5 to match EnvNet-v2 input size
        high: 0.5    # Fixed at 0.5 to match EnvNet-v2 input size
        log: false
      
      augment:
        # Time stretch for tempo variation (strong regularization)
        time_stretch:
          type: float
          low: 0.7   # Slow down audio (0.5-0.9 range)
          high: 1.4  # Speed up audio (1.1-2.0 range) 
          log: false
        
        # Gain shift for volume variation (strong regularization)
        gain_shift:
          type: float
          low: -8.0  # Reduce volume by up to 8dB
          high: 8.0  # Increase volume by up to 8dB
          log: false 
