_target_: src.models.leaf.LeafModel
num_classes: ${dataset.num_classes}
n_filters: 128
kernel_size: 401
sample_rate: 44100

# Dataset overrides to apply the same augmentation/preprocessing as EnvNet-v2
dataset_overrides:
  preprocessing_mode: envnet_v2
  is_spectrogram: false

  enable_mixup: false
  enable_bc_mixing: true

  augment:
    time_mask: false
    freq_mask: false

  preprocessing_config:
    window_length: 5.0
    padding_ratio: 0.5

    augment:
      time_stretch: null
      gain_shift: null



# Enables Optuna sweeper
defaults:
  - override hydra/sweeper: optuna

# Optuna Sweeper configuration
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    metric: val/acc  # replace with the actual metric key you log in validation_step
    n_trials: 50
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42