# =============================================================================
# ESC-50 Dataset Configuration (Consolidated)
# =============================================================================
# Pure dataset configuration - model-specific parameters are now in model configs
# Supports both AST and EnvNet-v2 models through model config overrides
# 
# USAGE:
# ======
# Model-specific settings are now defined in:
# - configs/model/ast.yaml (SpecAugment, spectrogram preprocessing)
# - configs/model/envnet_v2.yaml (waveform preprocessing, augmentation)
#
# Training examples:
# python train.py model=ast dataset=esc50
# python train.py model=envnet_v2 dataset=esc50
#
# NOTE: batch_size and num_workers are configured in configs/base_training.yaml
# =============================================================================

_target_: src.datasets.esc50.ESC50DataModule
root: data/processed/esc50
num_classes: 50
fold: 0                # Range: 0-4 (ESC-50 uses 5-fold CV)
val_split: 0.1         # Range: 0.0-0.5 (fraction of training data for validation)

# =============================================================================
# DATASET-SPECIFIC PARAMETERS
# =============================================================================
# NOTE: Augmentation settings (enable_mixup, enable_bc_mixing, mixup_alpha) are 
# model-specific and defined in model configs (model/ast.yaml, model/envnet_v2.yaml)
# 
# NOTE: preprocessing_mode is model-specific and defined in model configs

# Base preprocessing configuration (overridden by model configs)
sample_rate: 44100       # Standard audio sample rate

# =============================================================================
# DATALOADER CONFIGURATION  
# =============================================================================
# NOTE: batch_size and num_workers are configured in configs/base_training.yaml
# These values are passed directly to the datamodule constructor by the training script
pin_memory: true        # Boolean: faster GPU transfer
persistent_workers: true # Boolean: faster epoch transitions
