# configs/dataset/urbansound8k.yaml
_target_: src.datasets.urbansound8k.UrbanSound8KDataModule
root: data/urbansound8k
meta_csv: metadata/UrbanSound8K.csv
sample_rate: 44100        # original files are 44.1 kHz PCM
num_folds: 10
fold: 0
val_split: 0.1
augment:
  time_mask: false
  freq_mask: false
