defaults:
  - base_training
  - dataset: esc50
  - model: leaf
  - hydra/sweeper: optuna  # 💡 This tells Hydra to use Optuna for sweeps
  - _self_

hydra:
  run:
    dir: outputs/optimization/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

logging:
  experiment_name: optuna_leaf_esc50

model:
  _target_: src.models.leaf.LeafModel
  num_classes: ${dataset.num_classes}
  n_filters: 128        # Default, will be overridden by sweep
  kernel_size: 401      # Default, will be overridden by sweep
  sample_rate: 44100

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  weight_decay: 1e-4

# Optuna sweeper config
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    study_name: leaf_esc50_optuna
    storage: sqlite:///optuna_leaf_esc50.db
    n_trials: 50
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    search_space:
      model.n_filters:
        type: categorical
        choices: [64, 128, 256]
      model.kernel_size:
        type: categorical
        choices: [201, 401, 801]
      optimizer.lr:
        type: float
        low: 1e-5
        high: 1e-2
        log: true
      optimizer.weight_decay:
        type: float
        low: 1e-6
        high: 1e-2
        log: true

trainer:
  max_epochs: 50
