defaults:
  - base_training
  - dataset: esc50
  - model: leaf
  - _self_

logging:
  experiment_name: optuna_leaf_esc50

# -----------------------------------------------------------------------------
# Model Configuration (defaults overridden by Optuna during sweeps)
# -----------------------------------------------------------------------------
model:
  _target_: src.models.leaf.LeafModel
  num_classes: ${dataset.num_classes}
  n_filters: 128        # default (will be overridden)
  kernel_size: 401      # default (will be overridden)
  sample_rate: 44100

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  weight_decay: 1e-4

# -----------------------------------------------------------------------------
# Optuna Hyperparameter Optimization Configuration
# -----------------------------------------------------------------------------
optuna:
  # Core study settings
  study_name: "optuna_leaf_esc50"
  direction: "maximize"
  storage_path: "sqlite:///optuna_leaf_esc50.db"  # local SQLite DB
  n_trials: 50
  timeout: null

  # Sampler (TPE)
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 42

  # Pruner (Hyperband)
  pruner:
    _target_: optuna.pruners.HyperbandPruner
    min_resource: 1
    max_resource: 100
    reduction_factor: 3

  # Hyperparameter Search Space
  search_space:
    model.n_filters:
      type: categorical
      choices: [64, 128, 256]
    model.kernel_size:
      type: categorical
      choices: [201, 401, 801]
    optimizer.lr:
      type: float
      low: 1e-5
      high: 1e-2
      log: true
    optimizer.weight_decay:
      type: float
      low: 1e-6
      high: 1e-2
      log: true

  # MLflow Logging
  mlflow_experiment_name: "optuna_leaf_experiment"

  # Output Settings
  output_dir: "outputs/optimization"
  best_config_path: "best_config.yaml"
  monitor: "val/acc"
  mode: "max"
  min_epochs: 10
