defaults:
  - _self_
  - dataset: esc50
  - model: ast
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null

seed: 42

trainer:
  max_epochs: 10
  accelerator: auto        # picks GPU if available
  precision: 16-mixed      # mixed-precision
  devices: 1
  # log_every_n_steps will be set dynamically based on steps per epoch

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 100  # matches max_epochs

metric:
  _target_: torchmetrics.classification.Accuracy
  task: multiclass
  num_classes: ${dataset.num_classes}

batch_size: 32
num_workers: 8

logging:
  experiment_name: ast_esc50
checkpoint:
  monitor: val/acc
  mode: max
  dirpath: checkpoints
  save_top_k: 3 